import { Download, Palette, X } from 'lucide-react'
import { useState } from 'react'
import './style-export.css'

type Palette = { fill: string; hover: string; selected: string; border: string; background: string }
const presets: Array<{ id: string; label: string; palette: Palette }> = [
  { id: 'forest', label: 'Forest', palette: { fill: '#dbe9dc', hover: '#bed8c1', selected: '#4f8a61', border: '#ffffff', background: '#f6faf6' } },
  { id: 'cobalt', label: 'Cobalt', palette: { fill: '#dfe7ff', hover: '#bfd0ff', selected: '#4f6df2', border: '#f8fbff', background: '#f4f7ff' } },
  { id: 'sunset', label: 'Sunset', palette: { fill: '#fde6d5', hover: '#f7c3a5', selected: '#d76c4d', border: '#fffaf5', background: '#fff7f2' } },
  { id: 'midnight', label: 'Midnight', palette: { fill: '#dfe5ef', hover: '#b7c6d9', selected: '#3d5c87', border: '#edf3fb', background: '#f1f5fb' } },
]
const initial: Palette = presets[0].palette
const mapElement = (exportId: string) => document.querySelector<SVGSVGElement>(`[data-map-export-id="${exportId}"]`)
const apply = (exportId: string, palette: Palette, showLabels: boolean) => { const svg = mapElement(exportId); if (!svg) return; svg.style.setProperty('--region-fill', palette.fill); svg.style.setProperty('--region-hover', palette.hover); svg.style.setProperty('--region-selected', palette.selected); svg.style.setProperty('--region-border', palette.border); svg.style.background = palette.background; svg.style.setProperty('--label-opacity', showLabels ? '1' : '0') }
const svgSource = (exportId: string) => { const svg = mapElement(exportId); if (!svg) return null; const copy = svg.cloneNode(true) as SVGSVGElement; copy.setAttribute('xmlns', 'http://www.w3.org/2000/svg'); copy.setAttribute('width', '900'); copy.setAttribute('height', '620'); return new XMLSerializer().serializeToString(copy) }
const download = (content: BlobPart, type: string, name: string) => { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url) }

export function MapStyleExport({ exportId, filenameBase, mapLabel }: { exportId: string; filenameBase: string; mapLabel: string }) {
  const [open, setOpen] = useState(false)
  const [showLabels, setShowLabels] = useState(true)
  const [palette, setPalette] = useState(initial)
  const update = (key: keyof Palette, value: string) => { const next = { ...palette, [key]: value }; setPalette(next); apply(exportId, next, showLabels) }
  const selectPreset = (next: Palette) => { setPalette(next); apply(exportId, next, showLabels) }
  const exportSvg = () => { const source = svgSource(exportId); if (source) download(source, 'image/svg+xml;charset=utf-8', `${filenameBase}.svg`) }
  const exportPng = async () => { const source = svgSource(exportId); if (!source) return; const image = new Image(); image.onload = () => { const canvas = document.createElement('canvas'); canvas.width = 1800; canvas.height = 1240; const context = canvas.getContext('2d'); if (!context) return; context.fillStyle = palette.background; context.fillRect(0, 0, canvas.width, canvas.height); context.drawImage(image, 0, 0, canvas.width, canvas.height); canvas.toBlob((blob) => { if (blob) download(blob, 'image/png', `${filenameBase}.png`) }, 'image/png') }; image.src = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(source)}` }
  const exportJpg = async () => { const source = svgSource(exportId); if (!source) return; const image = new Image(); image.onload = () => { const canvas = document.createElement('canvas'); canvas.width = 1800; canvas.height = 1240; const context = canvas.getContext('2d'); if (!context) return; context.fillStyle = '#ffffff'; context.fillRect(0, 0, canvas.width, canvas.height); context.drawImage(image, 0, 0, canvas.width, canvas.height); canvas.toBlob((blob) => { if (blob) download(blob, 'image/jpeg', `${filenameBase}.jpg`) }, 'image/jpeg', 0.92) }; image.src = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(source)}` }
  return <><button className="style-fab" onClick={() => setOpen(true)} aria-label="رنگ و خروجی"><Palette size={19} /> رنگ و خروجی</button>{open && <div className="style-popover" role="dialog" aria-label="رنگ و خروجی نقشه"><header><strong>رنگ و خروجی نقشه</strong><button onClick={() => setOpen(false)} aria-label="بستن"><X size={18} /></button></header><p>رنگ‌ها برای نقشهٔ «{mapLabel}» اعمال می‌شوند و SVG یا PNG همان نما را دریافت می‌کنید.</p><div className="preset-grid">{presets.map((preset) => <button key={preset.id} className={palette.fill === preset.palette.fill ? 'is-active' : ''} onClick={() => selectPreset(preset.palette)}>{preset.label}</button>)}</div><label className="toggle-row"><span>نمایش برچسب‌ها</span><input type="checkbox" checked={showLabels} onChange={(event) => { setShowLabels(event.target.checked); apply(exportId, palette, event.target.checked) }} /></label><div className="color-grid">{([['fill', 'رنگ ناحیه'], ['hover', 'رنگ شناور'], ['selected', 'رنگ انتخاب'], ['border', 'مرزها'], ['background', 'پس‌زمینه']] as [keyof Palette, string][]).map(([key, label]) => <label key={key}>{label}<input type="color" value={palette[key]} onChange={(event) => update(key, event.target.value)} /></label>)}</div><button className="reset-style" onClick={() => { setPalette(initial); setShowLabels(true); apply(exportId, initial, true) }}>بازنشانی رنگ‌ها</button><div className="export-actions"><button onClick={exportSvg}><Download size={16} /> دریافت SVG</button><button onClick={exportPng}><Download size={16} /> دریافت PNG</button><button onClick={exportJpg}><Download size={16} /> دریافت JPG</button></div></div>}</>
}
