import { ArrowLeft, Braces, Database, MapPinned, MousePointer2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { usePageSeo } from '../app/seo'
import { SiteChrome } from '../components/SiteChrome'
import './about.css'

export function AboutPage() {
  usePageSeo({ title: 'راهنمای استفاده از نقشه', description: 'راهنمای عملی نقشهٔ ایران: انتخاب استان، ورود داده، استفاده از شناسه‌های پایدار و رندر در React.', path: '/about' })
  return <SiteChrome className="about-page"><main className="about-content"><section className="about-intro"><p>راهنمای استفاده</p><h1>مرز، داده و تصمیم؛ در یک سطح قابل‌فهم.</h1><span>نقشهٔ ایران برای محصولاتی است که باید وضعیت را ببینند، نه فقط موقعیت را.</span><Link className="about-cta" to="/map">باز کردن محیط نقشه <ArrowLeft size={17} /></Link></section><section className="about-steps" aria-label="مراحل استفاده"><article><MapPinned size={24} /><strong>ناحیه را انتخاب کنید</strong><p>نمای ایران را در سمت راست نگه دارید و برای بررسی دقیق، یک استان را باز کنید.</p></article><article><Database size={24} /><strong>داده را متصل کنید</strong><p>JSON یا CSV را با شناسهٔ پایدار `regionId` وارد کنید؛ نام فقط برای نمایش است.</p></article><article><MousePointer2 size={24} /><strong>معنا را بخوانید</strong><p>رنگ، مقدار و tooltip برای مقایسه‌اند؛ نقطهٔ شهر فقط یک مختصات مرجع است، نه مرز.</p></article></section><section className="about-grid"><article><h2>در نقشه چه چیزی واقعی است؟</h2><p>استان‌ها و شهرستان‌ها مرزهای برداری دارند. شهرها با نام، وابستگی شهرستانی و وضعیت مختصات نمایش داده می‌شوند. این تفاوت عمداً در رابط و داده‌ها جدا نگه داشته شده تا هیچ مرزی حدس زده نشود.</p><a href="https://github.com/Mobin-Karam/iran-vector-maps/blob/main/DATA_SOURCES.md" target="_blank" rel="noreferrer">منبع‌ها و محدودهٔ داده‌ها</a></article><article><h2>برای چه کاری مناسب است؟</h2><p>پایش پوشش خدمت، تحلیل جمعیت و تولد، شبکهٔ فروش، آموزش، سلامت، عملیات شهری و هر داشبوردی که داده را بر مبنای استان یا شهرستان مقایسه می‌کند.</p></article><article><Braces size={22} /><h2>برای توسعه‌دهنده</h2><p>رندرگر React از دادهٔ ایران جداست. مرزهای خودتان را بدهید یا بستهٔ داده را نصب کنید، سپس رنگ و تعامل را کاملاً در محصول خودتان کنترل کنید.</p><Link to="/package">مشاهدهٔ API و نصب</Link></article></section></main></SiteChrome>
}
